/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#4d8eff",
        "on-secondary-fixed-variant": "#005048",
        "on-secondary-fixed": "#00201c",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#472a00",
        "surface-bright": "#31394e",
        "tertiary-fixed-dim": "#ffb95f",
        "outline-variant": "#424754",
        "on-primary-fixed": "#001a42",
        "secondary-container": "#04b4a2",
        "secondary": "#4fdbc8",
        "tertiary-fixed": "#ffddb8",
        "primary-fixed-dim": "#adc6ff",
        "on-tertiary-fixed": "#2a1700",
        "tertiary-container": "#ca8100",
        "surface-dim": "#0b1326",
        "error-container": "#93000a",
        "surface-container-lowest": "#060d20",
        "surface-variant": "#2d3449",
        "inverse-on-surface": "#283044",
        "on-surface-variant": "#c2c6d6",
        "outline": "#8c909f",
        "surface-container-highest": "#2d3449",
        "surface-container-high": "#222a3e",
        "primary-fixed": "#d8e2ff",
        "on-tertiary-fixed-variant": "#653e00",
        "on-tertiary-container": "#3e2400",
        "error": "#ffb4ab",
        "tertiary": "#ffb95f",
        "on-primary": "#002e6a",
        "on-secondary-container": "#003f38",
        "secondary-fixed": "#71f8e4",
        "on-secondary": "#003731",
        "on-background": "#dbe2fd",
        "on-primary-fixed-variant": "#004395",
        "inverse-primary": "#005ac2",
        "secondary-fixed-dim": "#4fdbc8",
        "background": "#0b1326",
        "primary": "#adc6ff",
        "surface": "#0b1326",
        "inverse-surface": "#dbe2fd",
        "surface-tint": "#adc6ff",
        "surface-container-low": "#131b2e",
        "on-primary-container": "#00285d",
        "surface-container": "#171f33",
        "on-surface": "#dbe2fd",
        "on-error": "#690005"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
